### ISSUE TITLE
Problem with setup.py install

### ISSUE THREAD

**Issue by mexicantexan** [menpo/cyvlfeat#40]
Everything seems to be running fine with the install until cysift. Here is what I am getting out when I run 'setup.py install'. Everything up to that point seems to build correctly.

building 'cyvlfeat.sift.cysift' extension
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Icyvlfeat -IC:\U
sers\10dallasj\PycharmProjects\PPSuite\venv\lib\site-packages\numpy\core\include -IC:\Users\10dallasj\PycharmProjects\PPSuite\venv\include -IC:\include -IC:\include
"-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Bu
ildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.
17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program
 Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tccyvlfeat\sift\cysift.c /Fobuild\
temp.win-amd64-3.7\Release\cyvlfeat\sift\cysift.obj
cysift.c
c:\users\10dallasj\pycharmprojects\ppsuite\venv\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, di
sable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
cyvlfeat\vl/host.h(280): warning C4005: 'isnan': macro redefinition
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_math.h(276): note: see previous definition of 'isnan'
cyvlfeat\sift\cysift.c(645): fatal error C1083: Cannot open include file: 'cy_util.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status
2

**Comment by Ayatao** [comment]
Traceback (most recent call last):
  File "setup.py", line 97, in <module>
    build_extension_from_pyx('cyvlfeat/fisher/cyfisher.pyx'),
  File "setup.py", line 68, in build_extension_from_pyx
    include_dirs.append(os.environ['LIBRARY_INC'])
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'LIBRARY_INC'
